theme: jekyll-theme-merlot
title: Welcome to Ariana Williams homepage!
description: This is my capstone of my work in my undergraduate program for computer science at Southern New Hampshire University. 
